name: Graphs CI
on:
  repository_dispatch:
    types: [graphs]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Generate graphs
        uses: upptime/uptime-monitor@v1
        with:
          command: "graphs"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
