name: Static Site CI
on:
  repository_dispatch:
    types: [static-site]
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Generate site
        uses: upptime/uptime-monitor@v1
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
