name: Update Template CI
on:
  repository_dispatch:
    types: [update-template]
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Update template
        uses: upptime/uptime-monitor@v1
        with:
          command: "update-template"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
